### ISSUE TITLE
Tarea gulp para browsificar el código y conectarse a un backend

### ISSUE THREAD

**Issue by rodrigojv** [jokoframework/joko_spa_starter_kit#1]
Se necesita una tarea gulp que ejecute solamente `watch` y `browserSync`, sin correr ningún server HTTP.

Actualmente si uno ejecuta:
`npm run server:mock`

Se levanta un server express que devuelve unos JSON de prueba. Lo que se necesita es otro script similar para construir el código y conectarmos a un middleware en lugar de un servidor mock express.

Receta:
1. Agregar al package.json el script: `gulp dev`
2. Crear la tarea "dev" en gulpfile.js o bien en la carpeta tasks. Fijarse como están implementadas las demás tareas. Esta tarea debe ser similar a la tarea default, pero en lugar de correr browserify debe correr "watch" y "browserSync". 
3. Sobre el punto anterior. Para ejecutar watch y browserSync se puede copiar la tarea `serverMock.js` y conectar a una IP configurada por parámetros en lugar de un servidor mock. Recuerde que la idea es que con "dev" nos podamos conectar a un backend que posiblemente pueda estar corriendo en otro server.

**Comment by carloscarvallo** [comment]
Esta es una propuesta para el issue, no es lo mas optimo aun https://github.com/jokoframework/joko_spa_starter_kit/pull/2

**Comment by rodrigojv** [comment]
Cerrado con https://github.com/jokoframework/joko_spa_starter_kit/pull/2

Gracias @carloscarvallo por la contribución 👍 💯
